// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB0Bg7CLi6au10XGpHlpO3Zv5bhTG0Ad2o',
    appId: '1:736426823074:web:67754d50e370aae1a5f6fb',
    messagingSenderId: '736426823074',
    projectId: 'quick-fix-e8067',
    authDomain: 'quick-fix-e8067.firebaseapp.com',
    storageBucket: 'quick-fix-e8067.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAJ2w_ouX51yYg9MHUJCOziYSyZKQPtmuk',
    appId: '1:736426823074:android:1a3707e53a88edd7a5f6fb',
    messagingSenderId: '736426823074',
    projectId: 'quick-fix-e8067',
    storageBucket: 'quick-fix-e8067.firebasestorage.app',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyB0Bg7CLi6au10XGpHlpO3Zv5bhTG0Ad2o',
    appId: '1:736426823074:web:9ed7041dbe8c0855a5f6fb',
    messagingSenderId: '736426823074',
    projectId: 'quick-fix-e8067',
    authDomain: 'quick-fix-e8067.firebaseapp.com',
    storageBucket: 'quick-fix-e8067.firebasestorage.app',
  );
}
